name: panel_admin_click
description: Panel de administración para validar conductores de Click_v2
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_database: ^11.2.1
  firebase_storage: ^12.3.6
  
  # UI
  cupertino_icons: ^1.0.8
  web: ^1.1.0
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagen/taxi_2.png
