// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QmnEK36qat8Sam-Rpbu_mfOfAt1JtqQ',
    appId: '1:991435007163:android:2e7540b70584dea4d9b59e',
    messagingSenderId: '991435007163',
    projectId: 'click-express-de9b3',
    storageBucket: 'click-express-de9b3.appspot.com',
    databaseURL: 'https://click-express-de9b3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlMgNZNigdcDjco9Y4D2gZd0gh6-6Iy0',
    appId: '1:991435007163:ios:cbca8dd3db5a98edd9b59e',
    messagingSenderId: '991435007163',
    projectId: 'click-express-de9b3',
    storageBucket: 'click-express-de9b3.appspot.com',
    iosBundleId: 'com.example.clickV2',
    databaseURL: 'https://click-express-de9b3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlk0_ucFl6giOAjXfNuyrMs-B0b_M07c',
    appId: '1:991435007163:web:035a73629c52715ad9b59e',
    messagingSenderId: '991435007163',
    projectId: 'click-express-de9b3',
    authDomain: 'click-express-de9b3.firebaseapp.com',
    databaseURL: 'https://click-express-de9b3-default-rtdb.firebaseio.com',
    storageBucket: 'click-express-de9b3.firebasestorage.app',
    measurementId: 'G-RQ023RBBHY',
  );

}